import path from 'node:path';
import { fileURLToPath } from 'node:url';

import js from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import confusingBrowserGlobals from 'confusing-browser-globals';
import importPlugin from 'eslint-plugin-import';
import vue from 'eslint-plugin-vue';
import globals from 'globals';

const projectRoot = path.dirname(fileURLToPath(import.meta.url));
const javascriptFiles = [
  '*.js',
  '*.mjs',
  'config/**/*.js',
  'packages/syncloungeserver/src/**/*.js',
  'src/**/*.js',
  'test/**/*.js',
];
const vueFiles = ['src/**/*.vue'];
const lintFiles = [...javascriptFiles, ...vueFiles];

export default [
  {
    name: 'synclounge/ignores',
    ignores: ['**/dist/**', '**/node_modules/**'],
  },
  {
    ...js.configs.recommended,
    name: 'synclounge/eslint-recommended',
    files: lintFiles,
  },
  {
    ...importPlugin.flatConfigs.recommended,
    name: 'synclounge/import-recommended',
    files: lintFiles,
  },
  ...vue.configs['flat/recommended'].map((config) => ({
    ...config,
    files: config.files ?? vueFiles,
  })),
  {
    ...stylistic.configs.customize({
      indent: 2,
      quotes: 'single',
      semi: true,
      jsx: false,
    }),
    name: 'synclounge/style',
    files: lintFiles,
  },
  {
    name: 'synclounge/project-rules',
    files: lintFiles,
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    linterOptions: {
      // ESLint 9 reports stale directives by default; retain the previous
      // behavior until those comments can be cleaned up independently.
      reportUnusedDisableDirectives: 'off',
    },
    rules: {
      // Preserve the high-value correctness and maintainability rules from the
      // unsupported Airbnb preset that are not covered by recommended configs.
      'array-callback-return': ['error', { allowImplicit: true }],
      'arrow-body-style': ['error', 'as-needed', { requireReturnForObjectLiteral: false }],
      'block-scoped-var': 'error',
      camelcase: ['error', {
        properties: 'never',
        ignoreDestructuring: false,
        ignoreImports: false,
        ignoreGlobals: false,
      }],
      'consistent-return': 'error',
      curly: ['error', 'multi-line'],
      'default-case': ['error', { commentPattern: '^no default$' }],
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-notation': ['error', { allowKeywords: true }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'func-names': 'warn',
      'getter-return': ['error', { allowImplicit: true }],
      'grouped-accessor-pairs': 'error',
      'guard-for-in': 'error',
      'global-require': 'error',
      'max-classes-per-file': ['error', 1],
      'max-len': ['error', { code: 120 }],
      'new-cap': ['error', {
        newIsCap: true,
        capIsNew: false,
        capIsNewExceptions: ['Immutable.Map', 'Immutable.Set', 'Immutable.List'],
        properties: true,
      }],
      'no-alert': 'warn',
      'no-array-constructor': 'error',
      'no-await-in-loop': 'error',
      'no-bitwise': 'error',
      'no-buffer-constructor': 'error',
      'no-caller': 'error',
      'no-cond-assign': ['error', 'always'],
      'no-console': 'off',
      'no-constant-condition': 'warn',
      'no-constructor-return': 'error',
      'no-continue': 'error',
      'no-else-return': ['error', { allowElseIf: false }],
      'no-empty-function': ['error', { allow: ['arrowFunctions', 'functions', 'methods'] }],
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-implied-eval': 'error',
      'no-inner-declarations': 'error',
      'no-iterator': 'error',
      'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
      'no-label-var': 'error',
      'no-lone-blocks': 'error',
      'no-lonely-if': 'error',
      'no-loop-func': 'error',
      'no-multi-assign': 'error',
      'no-multi-str': 'error',
      'no-nested-ternary': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-require': 'error',
      'no-new-wrappers': 'error',
      'no-object-constructor': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': ['error', {
        props: true,
        ignorePropertyModificationsFor: ['state', 'el'],
      }],
      'no-plusplus': 'error',
      'no-promise-executor-return': 'error',
      'no-proto': 'error',
      'no-path-concat': 'error',
      'no-restricted-exports': ['error', { restrictedNamedExports: ['default', 'then'] }],
      'no-restricted-globals': ['error',
        ...confusingBrowserGlobals,
        { name: 'isFinite', message: 'Use Number.isFinite instead.' },
        { name: 'isNaN', message: 'Use Number.isNaN instead.' },
      ],
      'no-restricted-properties': ['error',
        { object: 'arguments', property: 'callee', message: 'arguments.callee is deprecated.' },
        { object: 'global', property: 'isFinite', message: 'Use Number.isFinite instead.' },
        { object: 'self', property: 'isFinite', message: 'Use Number.isFinite instead.' },
        { object: 'window', property: 'isFinite', message: 'Use Number.isFinite instead.' },
        { object: 'global', property: 'isNaN', message: 'Use Number.isNaN instead.' },
        { object: 'self', property: 'isNaN', message: 'Use Number.isNaN instead.' },
        { object: 'window', property: 'isNaN', message: 'Use Number.isNaN instead.' },
        { property: '__defineGetter__', message: 'Use Object.defineProperty instead.' },
        { property: '__defineSetter__', message: 'Use Object.defineProperty instead.' },
        { object: 'Math', property: 'pow', message: 'Use the exponentiation operator (**) instead.' },
      ],
      'no-return-assign': ['error', 'always'],
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow': 'error',
      'no-shadow-restricted-names': 'error',
      'no-throw-literal': 'error',
      'no-template-curly-in-string': 'error',
      'no-underscore-dangle': 'off',
      'no-undef-init': 'error',
      'no-unneeded-ternary': ['error', { defaultAssignment: false }],
      'no-unreachable-loop': 'error',
      'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
      'no-use-before-define': ['error', { functions: true, classes: true, variables: true }],
      'no-unused-vars': ['error', {
        vars: 'all',
        args: 'after-used',
        caughtErrors: 'none',
        ignoreRestSiblings: true,
      }],
      'no-unused-expressions': ['error', {
        allowShortCircuit: false,
        allowTernary: false,
        allowTaggedTemplates: false,
      }],
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-void': 'error',
      'object-shorthand': ['error', 'always', { avoidQuotes: true }],
      'one-var': ['error', 'never'],
      'operator-assignment': ['error', 'always'],
      'prefer-arrow-callback': ['error', { allowNamedFunctions: false, allowUnboundThis: true }],
      'prefer-const': ['error', { destructuring: 'any', ignoreReadBeforeAssign: true }],
      'prefer-destructuring': ['error', {
        VariableDeclarator: { array: false, object: true },
        AssignmentExpression: { array: true, object: false },
      }, { enforceForRenamedProperties: false }],
      'prefer-exponentiation-operator': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
      'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      radix: 'error',
      strict: ['error', 'never'],
      'symbol-description': 'error',
      'unicode-bom': ['error', 'never'],
      'valid-typeof': ['error', { requireStringLiterals: true }],
      'vars-on-top': 'error',
      yoda: 'error',

      // Match the previous Airbnb formatting choices where Stylistic's
      // modern defaults intentionally differ.
      '@stylistic/arrow-parens': ['error', 'always'],
      '@stylistic/brace-style': ['error', '1tbs', { allowSingleLine: true }],
      '@stylistic/no-confusing-arrow': ['error', { allowParens: true }],
      '@stylistic/comma-dangle': ['error', {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'always-multiline',
      }],
      '@stylistic/comma-style': ['error', 'last'],
      '@stylistic/computed-property-spacing': ['error', 'never'],
      '@stylistic/function-call-argument-newline': ['error', 'consistent'],
      '@stylistic/function-call-spacing': ['error', 'never'],
      '@stylistic/function-paren-newline': ['error', 'multiline-arguments'],
      '@stylistic/implicit-arrow-linebreak': ['error', 'beside'],
      '@stylistic/indent': ['error', 2, {
        SwitchCase: 1,
        VariableDeclarator: 1,
        outerIIFEBody: 1,
        FunctionDeclaration: { parameters: 1, body: 1 },
        FunctionExpression: { parameters: 1, body: 1 },
        CallExpression: { arguments: 1 },
        ArrayExpression: 1,
        ObjectExpression: 1,
        ImportDeclaration: 1,
        flatTernaryExpressions: false,
        ignoredNodes: [
          'JSXElement',
          'JSXElement > *',
          'JSXAttribute',
          'JSXIdentifier',
          'JSXNamespacedName',
          'JSXMemberExpression',
          'JSXSpreadAttribute',
          'JSXExpressionContainer',
          'JSXOpeningElement',
          'JSXClosingElement',
          'JSXFragment',
          'JSXOpeningFragment',
          'JSXClosingFragment',
          'JSXText',
          'JSXEmptyExpression',
          'JSXSpreadChild',
        ],
        ignoreComments: false,
        offsetTernaryExpressions: false,
      }],
      '@stylistic/indent-binary-ops': 'off',
      '@stylistic/linebreak-style': ['error', 'unix'],
      '@stylistic/lines-between-class-members': ['error', 'always', {
        exceptAfterSingleLine: false,
      }],
      '@stylistic/newline-per-chained-call': ['error', { ignoreChainWithDepth: 4 }],
      '@stylistic/max-statements-per-line': 'off',
      '@stylistic/member-delimiter-style': 'off',
      '@stylistic/multiline-ternary': 'off',
      '@stylistic/no-extra-parens': 'off',
      '@stylistic/no-extra-semi': 'error',
      '@stylistic/no-mixed-operators': ['error', {
        groups: [
          ['%', '**'],
          ['%', '+'],
          ['%', '-'],
          ['%', '*'],
          ['%', '/'],
          ['/', '*'],
          ['&', '|', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!=='],
          ['&&', '||'],
        ],
        allowSamePrecedence: false,
      }],
      '@stylistic/operator-linebreak': ['error', 'before', { overrides: { '=': 'none' } }],
      '@stylistic/nonblock-statement-body-position': ['error', 'beside'],
      '@stylistic/object-curly-newline': ['error', {
        ObjectExpression: { minProperties: 4, multiline: true, consistent: true },
        ObjectPattern: { minProperties: 4, multiline: true, consistent: true },
        ImportDeclaration: { minProperties: 4, multiline: true, consistent: true },
        ExportDeclaration: { minProperties: 4, multiline: true, consistent: true },
      }],
      '@stylistic/object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
      '@stylistic/one-var-declaration-per-line': ['error', 'always'],
      '@stylistic/padded-blocks': ['error', {
        blocks: 'never',
        classes: 'never',
        switches: 'never',
      }, { allowSingleLineBlocks: true }],
      '@stylistic/padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: 'directive', next: '*' },
        { blankLine: 'always', prev: '*', next: 'directive' },
        { blankLine: 'any', prev: 'directive', next: 'directive' },
      ],
      '@stylistic/quote-props': ['error', 'as-needed', {
        keywords: false,
        unnecessary: true,
        numbers: false,
      }],
      '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
      '@stylistic/semi-style': ['error', 'last'],
      '@stylistic/spaced-comment': ['error', 'always', {
        line: { exceptions: ['-', '+'], markers: ['=', '!', '/'] },
        block: { exceptions: ['-', '+'], markers: ['=', '!', ':', '::'], balanced: true },
      }],
      '@stylistic/type-annotation-spacing': 'off',
      '@stylistic/type-generic-spacing': 'off',
      '@stylistic/type-named-tuple-spacing': 'off',
      '@stylistic/switch-colon-spacing': ['error', { after: true, before: false }],
      '@stylistic/wrap-iife': ['error', 'outside', { functionPrototypeMethods: false }],

      'import/extensions': ['error', 'ignorePackages', {
        js: 'never',
        mjs: 'never',
        jsx: 'never',
      }],
      'import/first': 'error',
      'import/newline-after-import': 'error',
      'import/no-absolute-path': 'error',
      'import/no-amd': 'error',
      'import/no-cycle': 'error',
      'import/no-duplicates': 'error',
      'import/no-dynamic-require': 'error',
      'import/no-extraneous-dependencies': ['error', { devDependencies: true }],
      'import/no-import-module-exports': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-named-as-default': 'error',
      'import/no-named-as-default-member': 'error',
      'import/no-named-default': 'error',
      'import/no-relative-packages': 'error',
      'import/no-self-import': 'error',
      'import/no-unresolved': ['error', { ignore: ['^@/'] }],
      'import/no-useless-path-segments': ['error', { commonjs: true }],
      'import/no-webpack-loader-syntax': 'error',
      'import/order': ['error', { groups: [['builtin', 'external', 'internal']] }],
      'import/prefer-default-export': 'error',

      'vue/no-template-target-blank': 'off',
      'vue/no-v-text-v-html-on-component': 'off',
    },
    settings: {
      'import/resolver': {
        node: {
          extensions: ['.js', '.mjs', '.json'],
        },
        alias: {
          map: [['@', path.resolve(projectRoot, 'src')]],
          extensions: ['.js', '.mjs', '.vue', '.json'],
        },
      },
    },
  },
  {
    name: 'synclounge/browser-globals',
    files: ['src/**/*.{js,vue}'],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    name: 'synclounge/test-globals',
    files: ['src/__tests__/**/*.js'],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    name: 'synclounge/node-globals',
    files: javascriptFiles.filter((file) => !file.startsWith('src/')),
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    name: 'synclounge/vite-config-interop',
    files: ['vite.config.mjs'],
    rules: {
      // eslint-plugin-import does not resolve this package's ESM default through its exports map.
      'import/default': 'off',
    },
  },
];
